### PR TITLE
add instructions to run Skype with skype-poll-fix.so automatically

### PR DESCRIPTION
**Pull request by gmelikov**

### CODE REVIEW

**Comment by ValdikSS** [comment]
Does it really need bash to add environment variable?

**Comment by gmelikov** [comment]
It's the first solution I've found.Or we can make script and run it from .desktop, but it's the same.18:09, February 11, 2016, ValdikSS <notifications@github.com>: Does it really need bash to add environment variable? —Reply to this email directly or view it on GitHub.

**Comment by gmelikov** [comment]
Found the way to do it through env.

**Comment by ValdikSS** [comment]
Could you please squash your commit?

**Comment by gmelikov** [comment]
Made a clean pull request

**Pull request closed without merging**
